kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "guestbook-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: guestbook-operator
  apiGroup: rbac.authorization.k8s.io
