{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "FirstChart.serviceAccountName" . }}
  labels:
{{ include "FirstChart.labels" . | nindent 4 }}
{{- end -}}
