apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia-rs-expressions
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: prashanthsriram145/kubia
          ports:
            - containerPort: 8080
