apiVersion: batch/v1
kind: Job
metadata:
  name: kubia-job
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job
        ports:
          - containerPort: 8080