apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc-readiness
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: prashanthsriram145/kubia
          readinessProbe:
            exec:
              command:
              - ls
              - /var/ready
          ports:
            - containerPort: 8080
              protocol: TCP